in "../p-semantics.maude" .

mod P-STATEMENT-TEST
  is including P-SEMANTICS .

  ops M1 M2 : -> Id .

  op initCfg : -> Cell .

  ops m1 m2 : -> Stmt .

  eq m1
   = machine M1 ; {
       x : int ;
       y : int ;
     } .

  eq m2
   = machine M2 ; {
       a : int ;
       b : int ;
     } .

  eq initCfg = <k> m1 m2 </k> <state> .Map </state> .

endm

search initCfg =>! <k> .Stmt </k> <state> M1 |-> S1:Stmt M2 |-> S2:Stmt </state>
  such that S1:Stmt == m1 /\ S2:Stmt == m2 .

quit .
