in "../p-semantics.maude" .

mod P-CONFIGURATION-TEST is including P-SEMANTICS .

  ops M1 M2 : -> Id .

endm

--- Single Cell
red <k> x = x + 1 ; y = y + 2 ; </k> .
red <k> machine M1 ; { x = 2 ; } </k> .

--- Multiple Cells
red <k> x = x + 1 ; </k>
    <machines>
      M1 |-> machine M1 ; { x = 2 ; }
      M2 |-> machine M2 ; { x = 1 ; }
    </machines> .


red <machines>
      M1 |-> machine M1 ; { x = 2 ; }
      M2 |-> machine M2 ; { x = 1 ; }
    </machines>
    <state> x |-> 23 y |-> 4 </state> .


quit .


