in "../p-semantics.maude" .

mod P-CONFIGURATION-TEST is including P-SEMANTICS .

  ops M1 M2 : -> Id .

endm

--- Soup
red <soup> < 1 | x = 1 | .Map > </soup> .

--- Multiple Cells
red <k> x = x + 1 ; </k>
    <machines>
      M1 |-> machine M1 ; { x = 2 ; }
      M2 |-> machine M2 ; { x = 1 ; }
    </machines> .


red <machines>
      M1 |-> machine M1 ; { x = 2 ; }
      M2 |-> machine M2 ; { x = 1 ; }
    </machines>
    <soup>
      < 0 | x : int ; y : int ; | .Map >
    </soup> .

quit .

